### ISSUE TITLE
hailstorm_web provisioner fails for VirtualBox 5.2.6 and vagrant 2.0.2

### ISSUE THREAD

**Issue by sayantam** [3pillarlabs/hailstorm-sdk#36]
```
==> dev: Running provisioner: hailstorm_web (shell)...
    dev: Running: /var/folders/j2/kpb8q5q568g83tf4mzphgl6w4__sd2/T/vagrant-shell20180213-12751-1rpkxi0.sh
    dev: stdin: is not a tty
    dev: Reading package lists...
    dev: Building dependency tree...
    dev: Reading state information...
    dev: libmysqlclient-dev is already the newest version.
    dev: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    dev: Reading package lists...
    dev: Building dependency tree...
    dev: Reading state information...
    dev: nodejs is already the newest version.
    dev: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    dev: Required ruby-2.1.4 is not installed.
    dev: To install do: 'rvm install "ruby-2.1.4"'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/bin/bundle
    dev: Required ruby-2.1.4 is not installed.
    dev: To install do: 'rvm install "ruby-2.1.4"'
    dev: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
    dev: installing your bundle as root will break this application for all non-root
    dev: users on this machine.
    dev: Fetching gem metadata from https://rubygems.org/
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: Fetching gem metadata from https://rubygems.org/
    dev: .
    dev: Resolving dependencies...
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: .
    dev: Using rake 12.0.0
    dev: Using concurrent-ruby 1.0.5 (java)
    dev: Using aasm 4.12.1
    dev: Using i18n 0.8.6
    dev: Using json 1.8.6 (java)
    dev: Using minitest 5.10.3
    dev: Using thread_safe 0.3.6 (java)
    dev: Using tzinfo 1.2.3
    dev: Using activesupport 4.1.6
    dev: Using builder 3.2.3
    dev: Using erubis 2.7.0
    dev: Using actionview 4.1.6
    dev: Using rack 1.5.5
    dev: Using rack-test 0.6.3
    dev: Using actionpack 4.1.6
    dev: Using mime-types-data 3.2016.0521
    dev: Using mime-types 3.1
    dev: Using mail 2.6.6
    dev: Using actionmailer 4.1.6
    dev: Using activemodel 4.1.6
    dev: Using arel 5.0.1.20140414130214
    dev: Using activerecord 4.1.6
    dev: Using execjs 2.7.0
    dev: Using autoprefixer-rails 7.1.2.3
    dev: Using bundler 1.16.1
    dev: Using climate_control 0.2.0
    dev: Using cocaine 0.5.8
    dev: Using connection_pool 2.2.1
    dev: Using thor 0.19.4
    dev: Using railties 4.1.6
    dev: Using font-awesome-rails 4.3.0.0
    dev: Using hike 1.2.3
    dev: Using multi_json 1.12.1
    dev: Using jbuilder 2.6.4
    dev: Using jquery-rails 3.1.4
    dev: Fetching kgio 2.11.0
    dev: Installing kgio 2.11.0 with native extensions
    dev: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    dev: 
    dev: current directory:
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/kgio-2.11.0/ext/kgio
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/bin/jruby -r
    dev: ./siteconf20180213-29667-6i3ptq.rb extconf.rb
    dev: checking for CLOCK_MONOTONIC in time.h... RuntimeError: The compiler failed to
    dev: generate an executable file.
    dev: You have to install development tools first.
    dev: 
    dev: try_do at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:456
    dev: block in try_compile at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:571
    dev: with_werror at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:524
    dev: try_compile at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:571
    dev: macro_defined? at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:839
    dev: block in have_macro at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:974
    dev: block in checking_for at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:942
    dev: block in postpone at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:350
    dev: open at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:320
    dev: block in postpone at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:350
    dev: open at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:320
    dev: postpone at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:346
    dev: checking_for at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:941
    dev: have_macro at
    dev: /usr/local/rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/mkmf.rb:973
    dev:                  <main> at extconf.rb:5
    dev: *** extconf.rb failed ***
    dev: Could not create Makefile due to some reason, probably lack of necessary
    dev: libraries and/or headers.  Check the mkmf.log file for more details.  You may
    dev: need configuration options.
    dev: 
    dev: Provided configuration options:
    dev: 	--with-opt-dir
    dev: 	--without-opt-dir
    dev: 	--with-opt-include
    dev: 	--without-opt-include=${opt-dir}/include
    dev: 	--with-opt-lib
    dev: 	--without-opt-lib=${opt-dir}/lib
    dev: 	--with-make-prog
    dev: 	--without-make-prog
    dev: 	--srcdir=.
    dev: 	--curdir
    dev: 	--ruby=/usr/local/rvm/rubies/jruby-9.1.7.0/bin/jruby
    dev: 
    dev: To see why this extension failed to compile, please check the mkmf.log which can
    dev: be found here:
    dev: 
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/extensions/universal-java-1.8/2.3.0/kgio-2.11.0/mkmf.log
    dev: 
    dev: extconf failed, exit code 1
    dev: 
    dev: Gem files will remain installed in
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/kgio-2.11.0 for inspection.
    dev: Results logged to
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/extensions/universal-java-1.8/2.3.0/kgio-2.11.0/gem_make.out
    dev: 
    dev: An error occurred while installing kgio (2.11.0), and Bundler cannot continue.
    dev: Make sure that `gem install kgio -v '2.11.0'` succeeds before bundling.
    dev: 
    dev: In Gemfile:
    dev:   unicorn was resolved to 5.3.0, which depends on
    dev:     kgio
    dev: rake aborted!
    dev: Bundler::GemNotFound: Could not find kgio-2.11.0 in any of the sources
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in requested_specs'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<main>'
    dev: /usr/local/lib/hailstorm-web/config/boot.rb:1:in `<main>'
    dev: /usr/local/lib/hailstorm-web/config/boot.rb:4:in `<main>'
    dev: /usr/local/lib/hailstorm-web/config/application.rb:1:in `<main>'
    dev: /usr/local/lib/hailstorm-web/config/application.rb:1:in `(root)'
    dev: /usr/local/lib/hailstorm-web/Rakefile:1:in `(root)'
    dev: /usr/local/lib/hailstorm-web/Rakefile:4:in `block in (root)'
    dev: /usr/local/rvm/gems/jruby-9.1.7.0/bin/jruby_executable_hooks:15:in `<main>'
    dev: (See full trace by running task with --trace)
    dev: start: Job failed to start

```

**Comment by sayantam** [comment]
Fixed with PR #37
