### ISSUE TITLE
Unexpected Exception on setup command 

### ISSUE THREAD

**Issue by sayantam** [3pillarlabs/hailstorm-sdk#43]
Stacktrace -
```
ERROR 2018-05-30 18:04:19,311 main /vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:68:in `handle_error' - undefined method `jmeter' for #<Hailstorm::Model::Project:0x37fef327>
DEBUG 2018-05-30 18:04:19,312 main /vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:69:in `handle_error' - 
org/jruby/RubyBasicObject.java:1653:in `method_missing'
/usr/local/rvm/gems/jruby-9.1.7.0@hailstorm/gems/activemodel-4.2.8/lib/active_model/attribute_methods.rb:433:in `method_missing'
/vagrant/hailstorm-gem/lib/hailstorm/cli/view_renderer.rb:22:in `render_setup'
/vagrant/hailstorm-gem/lib/hailstorm/cli/cmd_executor.rb:36:in `execute_method_args'
/vagrant/hailstorm-gem/lib/hailstorm/cli/cmd_executor.rb:26:in `interpret_execute'
/vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:44:in `process_cmd_line'
/vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:122:in `start_cmd_loop'
/vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:38:in `process_commands'
./script/hailstorm:13:in `<main>'

```

**Comment by sayantam** [comment]
Fixed with PR #44
