### ISSUE TITLE
Exception on 'show' or 'show active' or 'show [arg] active'

### ISSUE THREAD

**Issue by sayantam** [3pillarlabs/hailstorm-sdk#46]
```
hs > show
[ERROR] undefined method `active' for #<Hailstorm::Model::Cluster::ActiveRecord_Associations_CollectionProxy:0x3421debd>
Did you mean?  acts_like?
[DEBUG] 
org/jruby/RubyBasicObject.java:1653:in `method_missing'
/usr/local/rvm/gems/jruby-9.1.7.0@hailstorm/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:136:in `method_missing'
/usr/local/rvm/gems/jruby-9.1.7.0@hailstorm/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:99:in `method_missing'
/vagrant/hailstorm-gem/lib/hailstorm/cli/cmd_executor.rb:52:in `block in query_relations_map'
org/jruby/RubyArray.java:1733:in `each'
org/jruby/RubyEnumerable.java:936:in `inject'
/vagrant/hailstorm-gem/lib/hailstorm/cli/cmd_executor.rb:51:in `query_relations_map'
/vagrant/hailstorm-gem/lib/hailstorm/cli/cmd_executor.rb:45:in `show'
/vagrant/hailstorm-gem/lib/hailstorm/cli/cmd_executor.rb:22:in `interpret_execute'
/vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:44:in `process_cmd_line'
/vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:122:in `start_cmd_loop'
/vagrant/hailstorm-gem/lib/hailstorm/controller/cli.rb:38:in `process_commands'
./script/hailstorm:13:in `<main>'

```

**Comment by sayantam** [comment]
Fixed with PR #47
